server:
 port: 8082
 
 
spring:
 datasource:
  url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
  username: root
  password: Kutubminar@1
  driverClassName: com.mysql.cj.jdbc.Driver
 jpa:
   hibernate:
    ddl-auto: update
 application: 
  name: PAYMENT-SERVICE
 config:
  import: configserver:http://localhost:9296 
