server:
 port: 8081
 
management:
 health:
  circuitbreakers:
   enabled: true
 endpoints:
  web:
   exposure:
    include: health
 endpoint: 
  health: 
   show-details: always
 
 
spring:
 datasource:
  url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
  username: root
  password: Kutubminar@1
  driverClassName: com.mysql.cj.jdbc.Driver
 jpa:
   hibernate:
    ddl-auto: update
 application: 
  name: ORDER-SERVICE
 config:
  import: configserver:http://localhost:9296 
 security: # Spring security 
  oauth2: 
   resourceserver:
    jwt: 
     issuer-uri: https://dev-30717030.okta.com/oauth2/default
   client: 
    registration: 
     internal-client:
      provider: okta 
      authorization-grant-type: client_credentials 
      scope: internal 
      client-id: 0oa9n7as0ye9qQyYW5d7
      client-secret: wG2vVFMi8L277KWpArpWoc1f-x0efQzyak0tquc_  
    provider: 
     okta: 
      issuer-uri: https://dev-30717030.okta.com/oauth2/default
      

resilience4j:
 circuitbreaker:
  instances:
   order-service:
    registerHealthIndicator: true
    event-consumer-buffer-size: 10
    failure-rate-threshold: 50
    minimum-number-of-calls: 3
    automatic-transition-from-open-to-half-open-enabled: true
    wait-duration-in-open-state: 5s
    permitted-number-of-calls-in-half-open-state: 3 
    sliding-window-size: 10 
    sliding-window-type: COUNT_BASED  
 
 
#Added below configuration in config server which is common for all microservices      
#eureka:
#  client:
#   register-with-eureka: true
#   fetch-registry: true
#   service-url:
#    defaultZone: http://localhost:8761/eureka/
#  instance:
#   hostname: localhost
